INSERT INTO PRODUTOS VALUES(
1,
'Nome do Produto',
GETDATE(),
'1234567890',
0
);

INSERT INTO PRODUTOS(CODIGO, DESCRICAO, EAN) VALUES(
2,
'Nome do Produto2',
'1234567890'
);

SELECT *
  FROM PRODUTOS
 WHERE DESCRICAO  LIKE '%PRODUTO&'

 SELECT COUNT(*) AS TOTAL
   FROM PRODUTOS

CREATE TABLE LOJA (
	CODIGO      INT			NOT NULL,
	NOME        VARCHAR(50) NOT NULL,
	IND_INATIVO INT			NOT NULL  DEFAULT 0,
	CONSTRAINT LOJA_PK PRIMARY KEY(CODIGO)
)
;

INSERT INTO LOJA(CODIGO, NOME) VALUES(1000, 'Filial Caruaru');
INSERT INTO LOJA(CODIGO, NOME) VALUES(2000, 'Filial João Pessoa');
INSERT INTO LOJA(CODIGO, NOME) VALUES(3000, 'Filial Recife');

SELECT * FROM LOJA

CREATE TABLE ESTOQUE(
	CODIGO_PRODUTO	INT		NOT NULL,
	CODIGO_FILIAL	INT		NOT NULL,
	QUANTIDADE		DECIMAL	NOT NULL DEFAULT 0,
	CONSTRAINT ESTOQUE_PK PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);

SELECT * FROM ESTOQUE

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS(CODIGO)

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_LOJA
		FOREIGN KEY (CODIGO_FILIAL)
		REFERENCES LOJA(CODIGO)

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (1, 1000, 10)

SELECT * 
	FROM ESTOQUE INNER 